name: Tests

on:
  push:
    branches-ignore:
      - "translations"
      - "dependabot/**"
  pull_request:

env:
  NODE: 14.x

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "${{ env.NODE }}"

      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run HTML validator
        run: npm run test:html

      - name: Run linkinator
        run: npm run test:linkinator
